run:
    skip-dirs:
        - gen

linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/cadence-bootstrap

linters:
    enable-all: true

service:
    golangci-lint-version: 1.17.x
